#backup1

Match User zfs-push-receiver
  AllowAgentForwarding no
  AllowTcpForwarding no
  AllowUsers *@127.0.0.1 # Replace with the actual IP address of workstation1 or use * to allow any host
  AuthenticationMethods publickey
  Banner none
  GatewayPorts no
  LogLevel VERBOSE
  MaxAuthTries 1
  PasswordAuthentication no
  PermitTTY no
  PermitTunnel no
  X11Forwarding no
